// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBwoejquPWDysrdGJFJ_Mq1GXRdAj1uM',
    appId: '1:305171563248:android:81649d3e2897672427b835',
    messagingSenderId: '305171563248',
    projectId: 'kratos-bw',
    storageBucket: 'kratos-bw.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3B9hV-dX8VXdY08tjoaXuLMAoA4OOrw',
    appId: '1:305171563248:ios:dc4f4c92da1911d427b835',
    messagingSenderId: '305171563248',
    projectId: 'kratos-bw',
    storageBucket: 'kratos-bw.firebasestorage.app',
    iosBundleId: 'com.projeto.fitness.fitApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkhr1eesbuz83yZWFDx_C61bfd3QNNoM',
    appId: '1:305171563248:web:b59472887b894e6027b835',
    messagingSenderId: '305171563248',
    projectId: 'kratos-bw',
    authDomain: 'kratos-bw.firebaseapp.com',
    storageBucket: 'kratos-bw.firebasestorage.app',
  );
}
